services:
  file-fastapi:
    build: .
    container_name: file-fastapi
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - file-pg
      - file-redis
    networks:
      - file-network


  file-pg:
    image: postgres:alpine3.21
    container_name: file-pg
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    networks:
      - file-network

  file-redis:
    image: redis:7.4.5-alpine3.21
    container_name: file-redis
    command: redis-server --requirepass password
    ports:
      - "6379:6379"
    networks:
      - file-network
networks:
  file-network:
     driver: bridge
