"""change some attribute name File model

Revision ID: 327f90336df9
Revises: 62a6e6c107fd
Create Date: 2025-04-19 14:17:51.463833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '327f90336df9'
down_revision: Union[str, None] = '62a6e6c107fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('uploaded_at', sa.DateTime(), nullable=False))
    op.add_column('file', sa.Column('content_type', sa.String(), nullable=False))
    op.drop_index('ix_file_upload_time', table_name='file')
    op.create_index(op.f('ix_file_content_type'), 'file', ['content_type'], unique=False)
    op.create_index(op.f('ix_file_uploaded_at'), 'file', ['uploaded_at'], unique=False)
    op.drop_column('file', 'upload_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('upload_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_file_uploaded_at'), table_name='file')
    op.drop_index(op.f('ix_file_content_type'), table_name='file')
    op.create_index('ix_file_upload_time', 'file', ['upload_time'], unique=False)
    op.drop_column('file', 'content_type')
    op.drop_column('file', 'uploaded_at')
    # ### end Alembic commands ###
