"""change upload_date to upload_time

Revision ID: 62a6e6c107fd
Revises: 71267b4386b8
Create Date: 2025-04-19 12:24:59.910513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62a6e6c107fd'
down_revision: Union[str, None] = '71267b4386b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('upload_time', sa.DateTime(), nullable=False))
    op.drop_index('ix_file_upload_date', table_name='file')
    op.create_index(op.f('ix_file_upload_time'), 'file', ['upload_time'], unique=False)
    op.drop_column('file', 'upload_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_file_upload_time'), table_name='file')
    op.create_index('ix_file_upload_date', 'file', ['upload_date'], unique=False)
    op.drop_column('file', 'upload_time')
    # ### end Alembic commands ###
