"""change some attribute name File model

Revision ID: 6fffb91565f5
Revises: 327f90336df9
Create Date: 2025-04-19 14:23:54.508766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fffb91565f5'
down_revision: Union[str, None] = '327f90336df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.create_index(op.f('ix_file_updated_at'), 'file', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_updated_at'), table_name='file')
    op.drop_column('file', 'updated_at')
    # ### end Alembic commands ###
