"""change file_extension mapping

Revision ID: cc25977df0a8
Revises: dd016fbaf0eb
Create Date: 2025-05-09 21:14:00.528415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc25977df0a8'
down_revision: Union[str, None] = 'dd016fbaf0eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('file_extension', sa.String(), nullable=False))
    op.create_index(op.f('ix_file_file_extension'), 'file', ['file_extension'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_file_extension'), table_name='file')
    op.drop_column('file', 'file_extension')
    # ### end Alembic commands ###
