"""add storage path for s3_object_key

Revision ID: dd016fbaf0eb
Revises: 6fffb91565f5
Create Date: 2025-04-19 22:33:28.199644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd016fbaf0eb'
down_revision: Union[str, None] = '6fffb91565f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('storage_path', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'file', ['storage_path'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'file', type_='unique')
    op.drop_column('file', 'storage_path')
    # ### end Alembic commands ###
